# Copyright 2015 Antony Riley
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "DuckCrates"
version: "${version}-${project.build.number}"
main: "org.cyberiantiger.minecraft.duckcrates.Main"
commands:
  claim:
    description: Claim your crates.
    usage: |
        /claim         - List crates available to you
        /claim daily   - Claim daily crates
        /claim <type>  - Claim <type> crates
        /claim reset   - Reset your claim status
        /claim reload  - Reload config
        /claim inspect - Check a players claim status
        /claim give <type> <amount> <player>
    permission: duckcrates.claim
permissions:
  duckcrates.*:
    default: op
    descripton: All duckcrates permissions.
    children:
      duckcrates.reload: true
      ducktrails.reset: true
      ducktrails.claim: true
      duckcrates.inspect: true
      duckcrates.give: true
  duckcrates.reload:
    default: op
    description: Allows reloading duckcrates.
  duckcrates.reset:
    default: op
    description: Reset your claim status.
  duckcrates.claim:
    default: true
    description: Allow use of the claim command.
  duckcrates.inspect:
    default: op
    description: Allow use of the inspect subcommand on other players.
  duckcrates.give:
    default: op
    description: Allow use of the give subcommand to give crates to yourself.